[package]
name = "rs-wgpu-learn"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bytemuck = { version = "1.22.0", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.26"
parking_lot = "0.12.3"
pollster = "0.4.0"
wgpu = "24.0.1"
winit = "0.30.9"
